name: RUN UNIT TESTS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fetest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.21.3

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      env:
        API_URL: ${{ secrets.API_URL }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

