name: Accessibility Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.21.3

    - name: Install dependencies
      run: npm install

    - name: Install Pa11y CI
      run: npm install -g pa11y-ci

    - name: Install HTML reporter
      run: npm install -g pa11y-ci-reporter-html

    - name: Run Pa11y CI
      run: pa11y-ci

    - name: Generate HTML report
      id: pa11y
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        pa11y-ci --reporter=pa11y-ci-reporter-html > "pa11y-report-$TIMESTAMP.html"
        echo "::set-output name=timestamp::$TIMESTAMP"
    
    - name: Archive HTML report
      uses: actions/upload-artifact@v2
      with:
        name: pa11y-report
        path: "pa11y-ci-report/pa11y-report-${{ steps.pa11y.outputs.timestamp }}.html"
    
