name: Run UI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.21.3

    - name: Install dependencies
      run: npm install
    
    - name: Install webdriver
      run: npm install webdriver-manager --save-dev
    
    - name: Update webdriver
      run: npx webdriver-manager update --versions.chrome [119.0.6045.158]

    - name: Start server
      run: npm start &
      env:
        CI: true
    
    - name: Wait for server
      run: sleep 60

    - name: Run UI tests
      run: npm run test-ui
