name: Run UI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: npm start & 
      env:
        API_URL: ${{ secrets.API_URL }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        TEST_VALID_USERNAME: ${{ secrets.TEST_VALID_USERNAME }}
        TEST_VALID_PASSWORD: ${{ secrets.TEST_VALID_PASSWORD }}
        TEST_VALID_ADMIN_USERNAME: ${{ secrets.TEST_VALID_ADMIN_USERNAME }}
        TEST_VALID_ADMIN_USERNAME: ${{ secrets.TEST_VALID_ADMIN_USERNAME }}
    
    - name: Wait for server
      run: sleep 10

    - name: Run UI tests
      run: npm run test-ui
      env:
        API_URL: ${{ secrets.API_URL }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        TEST_VALID_USERNAME: ${{ secrets.TEST_VALID_USERNAME }}
        TEST_VALID_PASSWORD: ${{ secrets.TEST_VALID_PASSWORD }}
