name: Run UI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.21.3

    - name: Install dependencies
      run: npm ci
    
    - name: Start server
      run: npm start &
      env:
        CI: true
    
    - name: Wait for server
      run: sleep 5

    - name: Run UI tests
      run: npm run test-ui
